# Generated by Django 4.2.2 on 2023-06-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome do Usuario'),
            preserve_default=False,
        ),
    ]
