# Generated by Django 4.2.2 on 2023-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Preço do Produto')),
                ('medida_produto', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Medida de Produto')),
            ],
            options={
                'db_table': 'listacompras',
            },
        ),
    ]
